# Generated by Django 4.1.3 on 2022-11-23 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="duration",
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name="recipe",
            name="rating",
            field=models.SmallIntegerField(default=0),
        ),
    ]
