# Generated by Django 4.1.3 on 2022-11-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="rating",
            field=models.SmallIntegerField(default=0),
        ),
    ]
