# Generated by Django 4.1.3 on 2022-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipestep",
            name="order",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
