# Generated by Django 4.1.3 on 2022-12-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_recipe_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="instruction",
            field=models.TextField(default=0),
        ),
    ]
