# Generated by Django 4.1.3 on 2022-12-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_recipe_amount_recipe_food_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="food_item",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="instruction",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="order",
        ),
    ]
